### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by hessammehr** [WasatchPhotonics/Wasatch.PY#1]
I have a functional Python 3 port of this library. If the maintainers of Wasatch.PY would like to host it here, I'd be happy to send a pull request, potentially against a new branch.

**Comment by mzieg** [comment]
Hi Hessam, sorry for the delayed response.  Wasatch.PY does now build and run under Python 3 (version 1.0.20 in Apr 2019, which probably should have merited a bigger version bump), so I'm going to mark this "resolved."

If you'd like to add something, we probably need to move this into a proper PyPi "pip" package!
