### ISSUE TITLE
Raman virtual device: RUN

### ISSUE THREAD

**Issue by mggluscevic59** [WasatchPhotonics/Wasatch.PY#58]
Hello,

Did everything as noted in Doc file. Sending the output.

Kind Regards!
![Screen Shot 2022-11-03 at 13 08 29](https://user-images.githubusercontent.com/37954021/199718168-0502cb36-8fe9-438f-84eb-645d08cb4a53.png)

**Comment by mggluscevic59** [comment]
@mzieg Hello. Sorry for late reply. Switched to demoVirtualFix. No error, but no reply. Sending an output.


![image](https://user-images.githubusercontent.com/37954021/204282573-772c81d0-52ca-4126-8b90-c11127fdc128.png)

P.S. feel free to send me e-mail reminder. My employee did not prioritise Virtual device, so not full time on it!

**Comment by mggluscevic59** [comment]
Ok,

I figured it out. You can access virtual from WP shell. Is it possible to use it for testing `Demo.py`?

Kind regards
P.S. will close the issue now, because shell virtual is working for me.

**Comment by rc14193** [comment]
> Ok,
> 
> I figured it out. You can access virtual from WP shell. Is it possible to use it for testing `Demo.py`?
> 
> Kind regards P.S. will close the issue now, because shell virtual is working for me.

It would be possible but would require modifying Demo.py. It would mean replacing the connection function's logic with the connection process for a virtual spectrometer as in demo-virtual.py

**Comment by mggluscevic59** [comment]
> > Ok,
> > I figured it out. You can access virtual from WP shell. Is it possible to use it for testing `Demo.py`?
> > Kind regards P.S. will close the issue now, because shell virtual is working for me.
> 
> It would be possible but would require modifying Demo.py. It would mean replacing the connection function's logic with the connection process for a virtual spectrometer as in demo-virtual.py

Yes, I see.

Currently Demo.py uses RealDevice class to connect. If "URI" string would be used to connect, then "MOCK" parameter could be passed.

Warmly waiting for improvements!
Keep me posted.
Engr. Gluscevic
