### ISSUE TITLE
Error using wasatch-shell.py

### ISSUE THREAD

**Issue by sungjinrc** [WasatchPhotonics/Wasatch.PY#79]
Hi.
When I use the get function, the README gives a value of 1, but when I use it, I get a SpectrometerResponse object.
Thank you.

wasatch-shell version 2.3.0 invoked (Wasatch.PY 2.1.29)
wp> open
1
wp> set_laser_enable on
1
wp> get_laser_enable
ERROR: unknown command: get_laser_enable
wp> get_laser_enabled
<SpectrometerResponse (1519689372688), ErrorLevel.ok, Keep Alive False, Poison Pill False, error_msg , incomplete False, progress 0>
wp> set_laser_enable off
1
wp> get_laser_enabled
<SpectrometerResponse (1519696285008), ErrorLevel.ok, Keep Alive False, Poison Pill False, error_msg , incomplete False, progress 0>
wp> get_laser_enabled
<SpectrometerResponse (1519689372688), ErrorLevel.ok, Keep Alive False, Poison Pill False, error_msg , incomplete False, progress 0>
wp>

**Comment by sungjinrc** [comment]
I print self.data to the __str__ of the spectrometerResponse and it comes out fine.

wasatch-shell version 2.3.0 invoked (Wasatch.PY 2.1.29)
wp> open
1
wp> get_laser_enabled
<False SpectrometerResponse (2727177347024), ErrorLevel.ok, Keep Alive False, Poison Pill False, error_msg , incomplete False, progress 0>
wp> set_laser_enabled on
ERROR: unknown command: set_laser_enabled
wp> set_laser_enable on
1
wp> get_laser_enabled
<True SpectrometerResponse (2727195473360), ErrorLevel.ok, Keep Alive False, Poison Pill False, error_msg , incomplete False, progress 0>
wp>

**Comment by mzieg** [comment]
Hi @sungjinrc, please try again with Wasatch.PY 2.1.32 and let us know if this resolves your issue.

**Comment by sungjinrc** [comment]
Thank you for your quick response and feedback. Have a great day
